server:
  port: 9999
spring:
  application:
    name: micoservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Williamrightone/ConcertConfig.git #yet updated
          username: Williamrightone
          password: xxxxx
          default-label: main
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    prefer-ip-address: true